window.portfolio = {
  taglines: {
    hero: ['Ship reliable backend systems.', 'Turn research into working products.', 'Debug what production actually breaks.', 'Build agentic AI that does real work.', 'Connect infra, data, and models.'],
    projects: ['Recovery, training, and food in one plan.', 'A queue that tells you when to leave.', 'Real-time state across two dashboards.', 'Signed requests, no guessing.', 'Built past the demo.'],
    research: ['5x BLEU over the GPT-4o-mini baseline.', '10,000 synthetic clinical notes, zero manual tagging.', 'Grade-7 readability, patient-facing.', 'LoRA + PPO on LLaMA 3.2-3B.', 'Peer-reviewed at EMNLP 2025.']
  },
  nowservingVideo: 'WHatLISNyA4',
  experiences: [
    { id:'morgan-stanley',company:'Morgan Stanley',role:'Software Engineer, AI',date:'Dec 2025 - Current',chapter:'01 / Production',headline:'Making complex systems dependable.',intro:'At Morgan Stanley, my work brings together the parts of engineering I care about most: reliable backend services, efficient data systems, and AI that fits into real engineering workflows.',story:'I develop and maintain Java/Spring Boot microservices that process more than a million transactions each month. The work goes beyond shipping an endpoint: tracing latency spikes, resolving production defects, and tuning the SQL queries behind the experience brought p95 response times below 200 milliseconds and improved data retrieval time by 35%.',second:'Alongside the service layer, I built Bedrock agent workflows with MCP servers on Lambda and ECS. Connecting Jira, Confluence, and Bitbucket through one agent interface helps engineers move between issue context, documentation, and code. EKS deployments, CloudWatch alerts, testing, and UAT support keep those systems operational.',metrics:[['1M+','Monthly transactions'],['10M+','Monthly ETL records'],['<200ms','p95 response time'],['35%','Retrieval-time improvement']],flow:[['Engineering context','Jira / Confluence / Bitbucket'],['Agent orchestration','Bedrock Agents + MCP'],['Tool execution','API Gateway / Lambda / ECS'],['Operations','EKS + CloudWatch']],tags:['Java','Spring Boot','SQL','Amazon Bedrock','MCP','AWS EKS','JUnit / PyTest'],chart:{title:'SQL retrieval time, normalized',before:100,after:65,note:'Relative time index: baseline = 100. The 35% reduction is reported in my resume.'}},
    {id:'umass',company:'UMass Lowell',role:'Research Assistant',date:'Aug 2024 - Jun 2025',chapter:'02 / Research',headline:'Helping patients understand their health.',intro:'A clinical note can be precise and still be difficult for a patient to understand. My research explored how small language models and a multi-agent approach could turn that complexity into clearer patient education.',story:'I developed a patient-education platform using LLaMA 3.2-3B, LoRA fine-tuning, and PPO-based reinforcement learning. To support training and evaluation, I engineered a GPT-4o-mini synthesis pipeline for 10,000 clinically diverse discharge notes and question-answer pairs across 14 disease categories.',second:'The system achieved a 5x BLEU improvement and a 5% BERTScore gain over the GPT-4o-mini baseline. The work led to an EMNLP 2025 Findings publication. Beyond the experiments, I documented results, collaborated with research teams, and taught technical workshops reaching 88 students.',metrics:[['10K+','Synthetic clinical notes'],['14','Disease categories'],['5x','BLEU improvement'],['EMNLP','2025 Findings']],flow:[['Synthetic data','Clinical notes + QA pairs'],['Adaptation','LLaMA 3.2-3B + LoRA'],['Optimization','Multi-agent + PPO'],['Evaluation','BLEU / BERTScore']],tags:['Python','LLaMA 3.2','LoRA','PPO','GPT-4o-mini','LLM Evaluation'],chart:{title:'Annotation cycle time, normalized',before:100,after:70,note:'Relative time index: baseline = 100. The synthesis pipeline reduced annotation cycle time by 30%.'}},
    {id:'hexaware',company:'Hexaware Technologies',role:'Software Engineer',date:'Jul 2020 - Nov 2023',chapter:'03 / Foundations',headline:'Turning live network data into action.',intro:'At Hexaware, I worked on a network-management platform for Wi-Fi infrastructure in airports and public venues. The goal was to help operations teams understand what was happening and respond sooner.',story:'I built monitoring dashboards with React, TypeScript, and Node.js, connecting live network and user-traffic data through WebSockets and REST APIs. Chart.js and D3.js visualizations translated streaming data into a view of network performance that operators could act on.',second:'The platform improved network uptime by 35%, reduced operations ticket volume by 22%, and cut mean incident detection time by 20%. I also deployed Docker-based backend services on AWS ECS with auto-scaling, maintaining 99.9% API availability over a six-month production window. Sprint planning, UAT, API documentation, and runbooks were part of delivering the complete system.',metrics:[['35%','Network uptime improvement'],['22%','Fewer operations tickets'],['20%','Faster incident detection'],['99.9%','API availability over 6 months']],flow:[['Network events','Wi-Fi infrastructure'],['Live transport','WebSockets + REST APIs'],['Operations view','React / Chart.js / D3.js'],['Service runtime','Node.js / Docker / ECS']],tags:['React','TypeScript','Node.js','WebSockets','Chart.js','D3.js','AWS ECS'],chart:{title:'Mean incident detection time, normalized',before:100,after:80,note:'Relative time index: baseline = 100. Resume-reported reduction in mean incident detection time: 20%.'}}
  ],
  fitlab: {
    name:'FitLive',repo:'https://github.com/kirann05/FitLive',stack:['React','TypeScript','Java 21','Spring Boot','PostgreSQL','SwiftUI'],
    intro:'A daily planning product that connects recovery, training, nutrition, and pantry stock to answer one useful question: what is the next sensible thing to do?',
    bullets:['Built a React/TypeScript fitness-planning application combining readiness check-ins, strength-session logging, deterministic progression, nutrition tracking, and pantry-aware shopping lists in a unified daily workflow.','Implemented a Java 21/Spring Boot and PostgreSQL account backend with signed web requests, versioned updates, and duplicate-operation handling; developed SwiftUI and HealthKit integration with native device verification pending.']
  }
};
